version: '3.8'

services:
  db:
    image: "postgres"
    env_file: .env
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - db

  bot:
    build: .
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      - DB_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/$POSTGRES_DATABASE
    networks:
      - db

volumes:
  db-data:

networks:
  db:
